home/urls.py
from django.urls import path, re_path
from .views import *

app_name = "home"
dispach = lambda path : path if "popularity" in path else ""
urlpatterns = [
    path("", home, name="home"),
    path("popularity", home, name="homePopularity"),
]

orders/urls.py
from django.urls import path
from .views import *

app_name = "cart"

urlpatterns = [
    path("", cart, name="cart"),
    path("checkout", Checkout.as_view(), name="checkout"),
    path("download/<int:order_id>", generatePdf, name="download"),
    path('add/<int:product_id>/', cart_add, name='cart_add'),
    path('decrease/<int:product_id>/', cart_decrease, name='cart_decrease'),
    path('remove/<int:product_id>/', cart_remove, name='cart_remove'),
]

setup/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import  static
from django.conf import settings
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("home.urls")),
    path("accounts/", include("accounts.urls")),
    path("category/", include("category.urls")),
    path("cart/", include("orders.urls")),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}, name='static'),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}, name='media'),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

orders/models.py
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField
from category.models import Products
from accounts.models import CustomUser

class Order(models.Model):
    user = models.ForeignKey(CustomUser, related_name="userOrders", on_delete=models.PROTECT, blank=True, null=True)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField()
    phone_number = PhoneNumberField(default = "+40")
    address = models.CharField(max_length=250)
    address2 = models.CharField(max_length=250, null=True, blank=True)
    postal_code = models.CharField(max_length=20)
    region = models.CharField(max_length=100)
    city = models.CharField(max_length=100)
    paiment_method = models.CharField(max_length=50)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    paid = models.BooleanField(default=False)
    
    class Meta:
        ordering = ('-created',)
        
    def __str__(self):
        return 'Order {}'.format(self.id)
    
    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all())
    
class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name='order', on_delete=models.CASCADE)
    product = models.ForeignKey(Products, related_name='order_items', on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)
    
    def __str__(self):
        return '{}'.format(self.id)
    
    def get_cost(self):
        return self.price * self.quantity

templates/cart/cart.html
{% extends 'base.html' %}
{% load static %}
{% load tags %}

{% block content %}
    <div class="container position-relative"  style="top: 70px; min-height: 100vh;">
        {% if cart %}
            <div class="table-responsive">
                <table class="table">
                    <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Image</th>
                        <th scope="col">Product</th>
                        <th scope="col">Price</th>
                        <th scope="col">Quantity</th>
                        <th scope="col">Ammount</th>
                    </tr>
                    </thead>
                    <tbody>
                        {% for item in cart %}
                            {% with product=item.product %}
                            <tr>
                                <th class="align-middle">
                                    {{ forloop.counter }} 
                                </th>
                                <th>
                                    {% if product.productImages.all|len != 0 %}
                                        {% for image in product.productImages.all %}
                                            {% if forloop.first %}
                                                <img class="img-fluid" src="{{ image.image.url }}" alt="{{ product.name }}" style="max-width: 150px;">
                                            {% endif %}
                                        {% endfor %}
                                    {% else %}
                                        <a href="{{ product.get_absolute_url }}">
                                            <img class="img-fluid" src="{% static 'Images/No_image.jpg' %}" alt="No Image" style="max-width: 150px;"/>
                                        </a>
                                    {% endif %}
                                </th>
                                <td class="align-middle">{{ product.name }}</td>
                                <td class="align-middle" style="min-width: 100px;">
                                    {% if product.deals.all|len != 0 %}
                                        {% for deal in product.deals.all %}
                                            <div class="fs.2 fw-bold text-decoration-line-through text-danger">{{ product.price }} LEi</div>
                                            <div class="ms-2 fs.2 fw-bold text-primary">{{ product.price|deals:deal}} LEi</div>
                                        {% endfor %}
                                    {% else %}
                                        <div class="fs.2 fw-bold">{{ product.price }} LEi</div>
                                    {% endif %}
                                </td>
                                <td class="align-middle">
                                    <div class="d-flex align-items-center">
                                        {{ item.quantity }}
                                        <div class="d-flex flex-row-reverse ">
                                            <form action="{% url 'cart:cart_add' product.id %}" method='post'>
                                                {{ add_to_cart }}
                                                {% csrf_token %}
                                                <button type="submit" class="cart-button btn btn-primary" style="border-bottom-right-radius: 20px;
                                                                                                                    border-top-right-radius: 20px;
                                                                                                                    border-bottom-left-radius: 0;
                                                                                                                    border-top-left-radius: 0;
                                                                                                                    ">
                                                    <i class="fas fa-chevron-right "></i>
                                                </button>
                                            </form>
                                            <form action="{% url 'cart:cart_decrease' product.id %}" method='post'>
                                                {{ add_to_cart }}
                                                {% csrf_token %}
                                                <button type="submit" class="ms-3 cart-button btn btn-primary" style="border-bottom-left-radius: 20px;
                                                                                                                    border-top-left-radius: 20px;
                                                                                                                    border-bottom-right-radius: 0;
                                                                                                                    border-top-right-radius: 0;
                                                                                                                    ">
                                                    <i class="fas fa-chevron-left "></i>
                                                </button>
                                            </form>
                                        </div>
                                    </div>
                                </td>
                                <td class="align-middle">
                                    {% if product.deals.all|len != 0 %}
                                        {% for deal in product.deals.all %}
                                            <div class="ms-2 fs.2 fw-bold text-primary">{{ product.price|deals:deal}} LEi</div>
                                        {% endfor %}
                                    {% else %}
                                        <div class="fs.2 fw-bold">{{ product.price }} LEi</div>
                                    {% endif %}
                                </td>
                            </tr>
                            {% endwith %}
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="d-flex justify-content-end my-3">
                <div class="fs-4 fw-semibold mx-2">
                    Total: {{ cart.get_total_price }} Lei
                </div>
                <a href="{% url 'cart:checkout' %}" class="btn btn-primary">
                    Complet Purchase
                </a>
            </div>
        {% else %} 
        <div class="text-center">
            No Products
        </div>
        {% endif %}
    </div>
    
{% endblock %}

templates/cart/checkout.html
{% extends 'base.html' %}
{% load static %}
{% load tags %}

{% block css %} 

{% endblock %}

{% block content %}

<style>
  #id_phone_number_0{
    width: 30%;
    margin-right: 10px;
  }
</style>
<div class="container position-relative my-3" style="top: 70px;">
    <div class="row g-5">
      <div class="col-md-5 col-lg-4 order-md-last">
        <h4 class="d-flex justify-content-between align-items-center mb-3">
          <span class="text-primary">Your cart</span>
          <span class="badge bg-primary rounded-pill">{{ cart.cart_products }}</span>
        </h4>
        <ul class="list-group mb-3">
          {% for item in cart %}
            {% with product=item.product %}
              <li class="list-group-item d-flex justify-content-between lh-sm">
                <div class="d-flex align-items-center">
                  {% if product.productImages.all|len != 0 %}
                      {% for image in product.productImages.all %}
                          {% if forloop.first %}
                              <img class="img-fluid" src="{{ image.image.url }}" alt="{{ product.name }}" style="max-width: 50px;">
                          {% endif %}
                      {% endfor %}
                  {% else %}
                    <a href="{{ product.get_absolute_url }}">
                        <img class="img-fluid" src="{% static 'Images/No_image.jpg' %}" alt="No Image" style="max-width: 50px;"/>
                    </a>
                  {% endif %}
                  <h6 class="my-1">{{ product.name }}</h6>
                </div>
                <span class="text-muted">
                  {% if product.deals.all|len != 0 %}
                      {% for deal in product.deals.all %}
                          <div class="fs.2 fw-bold text-decoration-line-through text-danger">{{ product.price }} LEi</div>
                          <div class="ms-2 fs.2 fw-bold text-primary">{{ product.price|deals:deal}} LEi</div>
                      {% endfor %}
                  {% else %}
                      <div class="fs.2 fw-bold">{{ product.price }} LEi</div>
                  {% endif %}
                </span>
              </li>
            {% endwith %}
          {% endfor %}
          <li class="list-group-item d-flex justify-content-between bg-light">
            <div class="text-success">
              <h6 class="my-0">Promo code</h6>
              <small>EXAMPLECODE</small>
            </div>
            <span class="text-success">−$5</span>
          </li>
          <li class="list-group-item d-flex justify-content-between">
            <span>Total</span>
            <strong>{{ cart.get_total_price }} Lei</strong>
          </li>
        </ul>
        <form class="card p-2">
          <div class="input-group">
            <input type="text" class="form-control" placeholder="Promo code">
            <button type="submit" class="btn btn-secondary">Redeem</button>
          </div>
        </form>
      </div>
      <div class="col-md-7 col-lg-8">
        <h4 class="mb-3">Billing address</h4>
        <form method="post" class="needs-validation {% if errors %} was-validated {% endif %}" novalidate>
          {% csrf_token %}
          <div class="row g-3">
            <div class="col-sm-6">
              <label for="id_first_name" class="form-label">First name</label>
              {{ form.first_name }}
              <div class="invalid-feedback">
                {% if  form.first_name.errors %}
                  {{ form.first_name.errors }}
                {% else %}
                  Valid first name is required.
                {% endif %}
              </div>
            </div>

            <div class="col-sm-6">
              <label for="id_last_name" class="form-label">Last name</label>
              {{ form.last_name }}
              <div class="invalid-feedback">
                {% if  form.last_name.errors %}
                  {{ form.last_name.errors }}
                {% else %}
                  Valid last name is required.
                {% endif %}
              </div>
            </div>

            <div class="col-12">
              <label for="id_email" class="form-label">Email</label>
              {{ form.email }}
              <div class="invalid-feedback">
                {% if  form.email.errors %}
                  {{ form.email.errors }}
                {% else %}
                  Please enter a valid email address for shipping updates.
                {% endif %}
              </div>
            </div>

            <div class="col-12">
              <label for="id_phone_number_1" class="form-label">Phone Number</label>
              <div class="d-flex justify-content-between">
                {{ form.phone_number }}
              </div>
              <div class="invalid-feedback">
                {% if  form.phone_number.errors %}
                  {{ form.phone_number.errors }}
                {% else %}
                  Please enter a valid phone number for shipping updates.
                {% endif %}
              </div>
            </div>

            <div class="col-12">
              <label for="id_address" class="form-label">Address</label>
              {{ form.address }}
              <div class="invalid-feedback">
                {% if  form.address.errors %}
                  {{ form.address.errors }}
                {% else %}
                  Please enter your shipping address.
                {% endif %}
              </div>
            </div>

            <div class="col-12">
              <label for="id_address2" class="form-label">Address 2 <span class="text-muted">(Optional)</span></label>
              {{ form.address2 }}
            </div>

            <div class="col-md-5">
              <label for="regions" class="form-label">Region</label>
              {{ form.region }}
              <div class="invalid-feedback">
                {% if  form.region.errors %}
                  {{ form.region.errors }}
                {% else %}
                  Please select a valid region.
                {% endif %}
              </div>
            </div>

            <div class="col-md-4">
              <label for="towns" class="form-label">Town</label>
              {{ form.city }}
              <div class="invalid-feedback">
                {% if  form.city.errors %}
                  {{ form.city.errors }}
                {% else %}
                  Please select a valid city.
                {% endif %}
              </div>
            </div>

            <div class="col-md-3">
              <label for="id_postal_code" class="form-label">Zip</label>
              {{ form.postal_code }}
              <div class="invalid-feedback">
                {% if  form.postal_code.errors %}
                  {{ form.postal_code.errors }}
                {% else %}
                  Zip code required.
                {% endif %}
              </div>
            </div>
          </div>

          <hr class="my-4">

          <div class="form-check">
            <input type="checkbox" class="form-check-input" id="same-address">
            <label class="form-check-label" for="same-address">Shipping address is the same as my billing address</label>
          </div>

          <div class="form-check">
            <input type="checkbox" class="form-check-input" id="save-info">
            <label class="form-check-label" for="save-info">Save this information for next time</label>
          </div>

          <hr class="my-4">

          <h4 class="mb-3">Payment</h4>

          <div class="my-3">
            {% for field in form.paiment_method %}
            <div class="form-check">
                {{ field }}
            </div>
            {% endfor %}
          </div>

          <hr class="my-4">
          
          <div class="w-100">
            <button class="btn btn-primary btn-lg" type="submit">Place the order</button>
          </div>
        </form>
      </div>
    </div>
</div>

{% endblock %}

{% block scripts %} 
    {% include 'cart/regions.html' %}
    {% include 'cart/towns.html' %}
    <script src="{% static 'js/checkout.js' %}"></script>
{% endblock %}

templates/cart/regions.html
<script id="regions_data" type="application/json">
    [
    {"region":"Alba"},
    {"region":"Arad"},
    {"region":"Arges"},
    {"region":"Bacau"},
    {"region":"Bihor"},
    {"region":"Bistrita-Nasaud"},
    {"region":"Botosani"},
    {"region":"Braila"},
    {"region":"Brasov"},
    {"region":"Bucuresti"},
    {"region":"Buzau"},
    {"region":"Calarasi"},
    {"region":"Caras-Severin"},
    {"region":"Cluj"},
    {"region":"Constanta"},
    {"region":"Covasna"},
    {"region":"Dambovita"},
    {"region":"Dolj"},
    {"region":"Galati"},
    {"region":"Giurgiu"},
    {"region":"Gorj"},
    {"region":"Harghita"},
    {"region":"Hunedoara"},
    {"region":"Ialomita"},
    {"region":"Iasi"},
    {"region":"Ilfov"},
    {"region":"Maramures"},
    {"region":"Mehedinti"},
    {"region":"Mures"},
    {"region":"Neamt"},
    {"region":"Olt"},
    {"region":"Prahova"},
    {"region":"Salaj"},
    {"region":"Satu Mare"},
    {"region":"Sibiu"},
    {"region":"Suceava"},
    {"region":"Teleorman"},
    {"region":"Timis"},
    {"region":"Tulcea"},
    {"region":"Valcea"},
    {"region":"Vaslui"},
    {"region":"Vrancea"}
    ]
</script>