accounts/urls.py
from django.urls import path
from django.contrib.auth.views import(
    LoginView,
    LogoutView
) 
from .views import *
from .forms import *

app_name = "accounts"

urlpatterns = [
    path("login/", LoginView.as_view(form_class = CustomAuthentificationForm ,template_name = "accounts/login.html"), name="login"),
    path("register/", register, name="register"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("orders/", downloadOrders, name="orders"),
]

home/urls.py
from django.urls import path, re_path
from .views import *

app_name = "home"
dispach = lambda path : path if "popularity" in path else ""
urlpatterns = [
    path("", home, name="home"),
    path("popularity", home, name="homePopularity"),
]

orders/urls.py
from django.urls import path
from .views import *

app_name = "cart"

urlpatterns = [
    path("", cart, name="cart"),
    path("checkout", Checkout.as_view(), name="checkout"),
    path("download/<int:order_id>", generatePdf, name="download"),
    path('add/<int:product_id>/', cart_add, name='cart_add'),
    path('decrease/<int:product_id>/', cart_decrease, name='cart_decrease'),
    path('remove/<int:product_id>/', cart_remove, name='cart_remove'),
]

setup/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import  static
from django.conf import settings
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("home.urls")),
    path("accounts/", include("accounts.urls")),
    path("category/", include("category.urls")),
    path("cart/", include("orders.urls")),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}, name='static'),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}, name='media'),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

accounts/models.py
from django.contrib.auth.models import(
    AbstractBaseUser,
    PermissionsMixin
)  
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _

from .managers import CustomUserManager


class CustomUser(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(_('email address'), unique=True)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    date_joined = models.DateTimeField(default=timezone.now)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

    def __str__(self):
        return self.email

orders/models.py
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField
from category.models import Products
from accounts.models import CustomUser

class Order(models.Model):
    user = models.ForeignKey(CustomUser, related_name="userOrders", on_delete=models.PROTECT, blank=True, null=True)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField()
    phone_number = PhoneNumberField(default = "+40")
    address = models.CharField(max_length=250)
    address2 = models.CharField(max_length=250, null=True, blank=True)
    postal_code = models.CharField(max_length=20)
    region = models.CharField(max_length=100)
    city = models.CharField(max_length=100)
    paiment_method = models.CharField(max_length=50)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    paid = models.BooleanField(default=False)
    
    class Meta:
        ordering = ('-created',)
        
    def __str__(self):
        return 'Order {}'.format(self.id)
    
    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all())
    
class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name='order', on_delete=models.CASCADE)
    product = models.ForeignKey(Products, related_name='order_items', on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)
    
    def __str__(self):
        return '{}'.format(self.id)
    
    def get_cost(self):
        return self.price * self.quantity

accounts/forms.py
from django.contrib.auth.forms import(
    UserCreationForm,
    UserChangeForm,
    AuthenticationForm
)   
from .models import(
    CustomUser
) 
from django import forms

class CustomUserCreationForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super(CustomUserCreationForm, self).__init__(*args, **kwargs)  
        self.fields['email'] = forms.CharField(widget=forms.TextInput(attrs={"placeholder":"name@example.com","class":"form-control"}))
        self.fields['password1'] = forms.CharField(widget=forms.PasswordInput(attrs={"placeholder":"Password","class":"form-control"}))
        self.fields['password2'] = forms.CharField(widget=forms.PasswordInput(attrs={"placeholder":"Confirm Password","class":"form-control"}))

    class Meta:
        model = CustomUser
        fields = ('email',"password1", "password2")

class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = CustomUser
        fields = ('email',)

class CustomAuthentificationForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={"placeholder":"name@example.com","class":"form-control"}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={"placeholder":"Password", "class":"form-control"}))

orders/forms.py
from django import forms
from .models import *
from phonenumber_field.widgets import PhoneNumberPrefixWidget

class CartAddProductForm(forms.Form):
    override = forms.BooleanField(required=False,
                                  initial=False,
                                  widget=forms.HiddenInput)

class CartDecreaseProductForm(CartAddProductForm):
    pass

Payment_CHICHES = (
    ("cash", "Cash on delivery"),
    ("credit_card", "Credit card"),
    ("debit_card", "Debit card"),
    ("paypal", "PayPal")
)

class CheckoutForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = [
            "first_name", 
            "last_name", 
            "email", 
            "phone_number",
            "address",
            "address2",
            "region",
            "city",
            "paiment_method",
            "postal_code"
            ]
        widgets = {
            "first_name":forms.TextInput(attrs={
                "class":"form-control"
            }),
            "last_name":forms.TextInput(attrs={
                "class":"form-control"
            }),
            "email":forms.EmailInput(attrs={
                "class":"form-control",
                "Placeholder":"you@example.com"
            }),
            "phone_number":PhoneNumberPrefixWidget(attrs={
                "class":"form-control",
                "Placeholder":"722222222",
                "type":"tel"
            },initial="RO"),
            "address":forms.TextInput(attrs={
                "class":"form-control",
                "Placeholder":"1234 Main St",
            }),
            "address2":forms.TextInput(attrs={
                "class":"form-control",
                "Placeholder":"Apartment or suite",
            }),
            "region":forms.Select(attrs = {
                "id":"regions",
                "class":"form-select",
                "required":""
            }),
            "city":forms.Select(attrs = {
                "id":"towns",
                "class":"form-select",
                "disabled":"",
                "required":""
            }),
            "postal_code":forms.TextInput(attrs={
                "class":"form-control"
            }),
            "paiment_method":forms.RadioSelect(attrs = {
                "class":"form-check-input",
                
            },choices=Payment_CHICHES ),
        }

accounts/views.py
from django.shortcuts import render, redirect
from .forms import CustomUserCreationForm
from django.contrib.auth.decorators import login_required
from orders.models import Order

def register(request):
    template_name = "accounts/register.html"
    registerForm = CustomUserCreationForm()

    if request.method == "POST":
        registerForm = CustomUserCreationForm(request.POST)
        if registerForm.is_valid():
            registerForm.save()
            return redirect("accounts:login")
    else:
        registerForm = CustomUserCreationForm()

    context = {
        "form": registerForm,
    }
    
    return render(request, template_name, context)

@login_required
def downloadOrders(request):
    template = "accounts/orders.html"
    orders = Order.objects.filter(user_id = request.user.id)
    context = {
        "orders":orders
    }
    return render(request, template, context)

orders/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from django.http import HttpResponse
from category.models import Products
from .cart import Cart
from .forms import *
from django.views.decorators.csrf import requires_csrf_token
from django.views.generic import TemplateView, View
from django.contrib import messages
from .models import *
from .process import html_to_pdf 
from django.contrib.auth.decorators import login_required


def cart(request):
    cart = Cart(request)
    template = "cart/cart.html"
    
    add_item_form = CartAddProductForm()
    decrease_item_form = CartDecreaseProductForm()

    context = {
        "cart":cart,
        "add":add_item_form,
        "decrease":decrease_item_form
    }
    return render(request, template, context)

class Checkout(TemplateView):
    template = "cart/checkout.html"
    context = {}

    def get(self, request):
        checkout = CheckoutForm()
        self.context["form"] = checkout
        self.context["errors"] = False
        return render(request, self.template, self.context)

    def post(self, request):
        cart = Cart(request)
        checkoutform = CheckoutForm(request.POST)
        if request.method == "POST":
            if checkoutform.is_valid():
                if request.user.id:
                    checkout = checkoutform.save(commit=False)
                    checkout.user_id = request.user.id
                    checkout.save()
                else:
                    checkout = checkoutform.save()
                for item in cart:
                    OrderItem.objects.create(
                        order_id = checkout.pk,
                        product_id = item["product"].id,
                        quantity = item["quantity"],
                        price = item["quantity"] * item["price"]
                        )
                cart.clear()
                messages.success(request, "Your order has been placed" )
                return redirect("home:home")          
            else:
                self.context["form"] = CheckoutForm(request.POST)
                self.context["errors"] = True
                return render(request, self.template, self.context)
        else:
            self.context["form"] = CheckoutForm()
               

@requires_csrf_token
@require_POST
def cart_add(request, product_id):
    print(request.path_info)
    cart = Cart(request)
    product = get_object_or_404(Products, id=product_id)
    form = CartAddProductForm(request.POST)
    print(form.errors)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=1,
                 override_quantity=cd['override'])
    return HttpResponse(status = 100)

def cart_decrease(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Products, id=product_id)
    form = CartDecreaseProductForm(request.POST)
    print(form.errors)
    if form.is_valid():
        cart.decrease(product=product)
    return HttpResponse(status = 100)


@require_POST
def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Products, id=product_id)
    cart.remove(product)
    return HttpResponse(status = 100)




@login_required
def generatePdf(request, order_id):
    template = "order/download.html"
    data = OrderItem.objects.filter(order_id = order_id)
    context = {
        "data":data
    }

    pdf = html_to_pdf(template, context_dict = context)

    return HttpResponse(pdf, content_type='application/pdf')

templates/accounts/login.html
{% load static %}
{% load bootstrap5 %}
{% load fontawesome_5 %}

<!DOCTYPE html>
<html lang="en">
  <head>
      <meta charset="UTF-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">

      {% bootstrap_css %}
      {% bootstrap_javascript %}
      {% fontawesome_5_static %}
      <title>Document</title>
  </head>
  <body class="bg-light">
    <div class="form-signin w-100 text-center">
        <form method = "POST" class="position-absolute top-50 start-50 translate-middle" style="width: 300px;">
        {% csrf_token %}
          <img class="mb-4" src="https://www.rcpe.ac.uk/sites/default/files/yourlogo.png" alt="" width="72" height="57">
          <h1 class="h3 mb-3 fw-normal">Please sign in</h1>
          <div class="form-floating">
            {{ form.username }}
            <label for="id_username">Email address</label>
          </div>
          <div class="form-floating">
            {{ form.password }}
            <label for="id_password">Password</label>
          </div>
          <div class="mb-3 text-muted">
              Don't have an account?
              <a href="{% url 'accounts:register' %}" class="text-primary">Create</a>
          </div>
          <button class="w-100 btn btn-lg btn-primary" type="submit">Sign in</button>
        </form>
    </div>
  </body>
</html>

templates/accounts/orders.html
{% extends 'base.html' %}
{% load static %}
{% load tags %}

{% block content %}
    <div class="position-relative container" style="top: 70px; height: 100vh;">
        {% for order in orders %}
            <div class="table-responsive mb-3">
                <table class="table table-striped table-sm">
                    <thead>
                        <tr>
                        <th scope="col">#</th>
                        <th scope="col">Product</th>
                        <th scope="col">Price</th>
                        <th scope="col">Quantity</th>
                        <th scope="col">Ammount</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for item in order.order.all %}
                            <tr>
                                <td>{{ forloop.counter }}</td>
                                <td>{{ item.product }}</td>
                                <td>{{ item.product.price }}</td>
                                <td>{{ item.quantity }}</td>
                                <td>{{ item.price }}</td>
                                
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
                <div class="w-100 d-flex justify-content-between">
                    <div>
                        total: {{ order.order.all.values|totalPrice }} <br>
                        Date: {{ order.created }}
                    </div>
                    <div>
                        <a class="btn btn-primary" href="{% url 'cart:download' order.id %}">Download PDF</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
  {% endblock %}

templates/accounts/register.html
{% load static %}
{% load bootstrap5 %}
{% load fontawesome_5 %}

<!DOCTYPE html>
<html lang="en">
  <head>
      <meta charset="UTF-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">

      {% bootstrap_css %}
      {% bootstrap_javascript %}
      {% fontawesome_5_static %}
      <title>Document</title>
  </head>
  <body class="bg-light">
    <div class="form-signin w-100 text-center">
        <form method = "POST" class="position-absolute top-50 start-50 translate-middle" style="width: 300px;">
        {% csrf_token %}
          <img class="mb-4" src="https://www.rcpe.ac.uk/sites/default/files/yourlogo.png" alt="" width="72" height="57">
          <h1 class="h3 mb-3 fw-normal">Register</h1>
          <div class="form-floating">
            {{ form.email }}
            <label for="id_username">Email address</label>
            {% if form.email.errors %}
                <small class="text-danger" >{{ form.email.errors }}</small> 
            {% endif %}
          </div>
          <div class="form-floating">
            {{ form.password1 }}
            <label for="floatingPassword">Password</label>
            {% if form.password1.errors %}
                <small class="text-danger" >{{ form.password1.errors }}</small> 
            {% endif %}
          </div>
          <div class="form-floating">
            {{ form.password2 }}
            <label for="floatingPassword">Confitm Password</label>
            {% if form.password2.errors %}
                <small class="text-danger" >{{ form.password2.errors }}</small> 
            {% endif %}
          </div>
          <div class="mb-3 text-muted">
                Have an account?
                <a href="{% url 'accounts:login' %}" class="text-primary">Login</a>
          </div>
          <button class="w-100 btn btn-lg btn-primary" type="submit">Register</button>
        </form>
    </div>
  </body>
</html>