category/urls.py
from django.urls import path
from .views import *

app_name = "category"

urlpatterns = [
    path("raiting", raiting, name="raiting"),
    path("product/<product_slug>", product, name="product"),
    path("<slug>", products_by_category, name="products_category"),
    path("<category_brand>/<category_slug>", products_by_brands, name="product_brands"),
]

home/urls.py
from django.urls import path, re_path
from .views import *

app_name = "home"
dispach = lambda path : path if "popularity" in path else ""
urlpatterns = [
    path("", home, name="home"),
    path("popularity", home, name="homePopularity"),
]

orders/urls.py
from django.urls import path
from .views import *

app_name = "cart"

urlpatterns = [
    path("", cart, name="cart"),
    path("checkout", Checkout.as_view(), name="checkout"),
    path("download/<int:order_id>", generatePdf, name="download"),
    path('add/<int:product_id>/', cart_add, name='cart_add'),
    path('decrease/<int:product_id>/', cart_decrease, name='cart_decrease'),
    path('remove/<int:product_id>/', cart_remove, name='cart_remove'),
]

setup/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import  static
from django.conf import settings
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("home.urls")),
    path("accounts/", include("accounts.urls")),
    path("category/", include("category.urls")),
    path("cart/", include("orders.urls")),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}, name='static'),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}, name='media'),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

category/models.py
from django.db import models 
from django.urls import reverse 
from accounts.models import CustomUser
from fontawesome_5.fields import IconField

class Brands(models.Model):
    title = models.TextField(max_length=50)
    slug = models.SlugField(unique=True, null=True, blank=True)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.slug = self.title.replace(" ", "_")
        super(Brands, self).save(*args, **kwargs)

class Category(models.Model):
    brands = models.ManyToManyField(Brands ,related_name="brands")
    title = models.TextField(max_length=100)
    image = IconField()
    svg = models.TextField(null=True, blank=True)
    slug = models.SlugField(unique=True, null=True, blank=True)

    def get_absolute_url(self):
        pass

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.slug = self.title.replace(" ", "_")
        super(Category, self).save(*args, **kwargs)

class Products(models.Model):
    brand = models.ForeignKey(Brands, null=True, on_delete=models.CASCADE, related_name="productBrands")
    category = models.ForeignKey(Category, null=True, blank=True, on_delete=models.CASCADE, related_name="productsCategory")
    name = models.TextField(max_length=100)
    description = models.TextField()
    price = models.DecimalField(max_digits = 10, decimal_places = 2)
    discount = models.FloatField(default=0)
    slug = models.SlugField(unique=True, null=True, blank=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('category:product',  args=[self.slug])

    def save(self, *args, **kwargs):
        self.slug = self.name.replace(" ", "-")
        super(Products, self).save(*args, **kwargs)

class ProductsDetails(models.Model):
    product = models.ForeignKey(Products,on_delete=models.CASCADE, related_name="productDetails")
    detail_name = models.CharField(max_length=50)
    detail_value = models.CharField(max_length=100)

    def __str__(self):
        return self.product.name + " " + self.detail_name

class ProductRaiting(models.Model):
    user =  models.ForeignKey(CustomUser, null=True, blank=True, on_delete=models.CASCADE)
    product = models.ForeignKey(Products,on_delete=models.CASCADE, related_name="productRaiting")
    raiting = models.DecimalField(default = 5, max_digits=2, decimal_places=1)
    message = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.product.name + " " + str(self.raiting)

class ProductImages(models.Model):
    product = models.ForeignKey(Products,on_delete=models.CASCADE, related_name="productImages")
    image = models.ImageField(upload_to = "images/Products")

    def __str__(self):
        return self.product.name + " " + "Image"

category/views.py
from django.shortcuts import render, get_object_or_404, get_list_or_404, HttpResponse
from .models import *
from django.db.models import FilteredRelation
from django.contrib import messages
from accounts.models import CustomUser
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

def products_by_category(request, slug ):

    template = "category/category_products.html"
    category = get_object_or_404 (Category, slug = slug)
    products = Products.objects.filter(category = category)
    section = "all"

    try:
        if "low" in request.GET["args"]:
            products =Products.objects.filter(category = category).order_by("price")
            section = "low"
        elif "hight" in request.GET["args"]:
            products =Products.objects.filter(category = category).order_by("-price")
            section = "hight"
        elif "popularity" in request.GET["args"]:
            products = Products.objects.filter(category = category).prefetch_related("productRaiting").order_by("-productRaiting")
            section = "popularity"

        raiting_filters = {
            "starone":Products.objects.filter(
                category = category
                ).annotate(
                    products = FilteredRelation(
                        "productRaiting" 
                        )
                    ).filter(products__raiting = 1),
            "startwo":Products.objects.filter(
                category = category
                ).annotate(
                    products = FilteredRelation(
                        "productRaiting" 
                        )
                    ).filter(products__raiting = 2),
            "starthree":Products.objects.filter(
                category = category
                ).annotate(
                    products = FilteredRelation(
                        "productRaiting" 
                        )
                    ).filter(products__raiting = 3),
            "starfour":Products.objects.filter(
                category = category
                ).annotate(
                    products = FilteredRelation(
                        "productRaiting" 
                        )
                    ).filter(products__raiting = 4),
        }
        for key, values in raiting_filters.items():
            if key == request.GET["args"]:
                products = values
                section = key

    except:
        pass

    page_num = request.GET.get('page', 1)
    paginator = Paginator(products, 8)

    try:
        products = paginator.page(page_num)
    except PageNotAnInteger:
        # if page is not an integer, deliver the first page
        products = paginator.page(1)
    except EmptyPage:
        # if the page is out of range, deliver the last page
        products = paginator.page(paginator.num_pages)

    context = {
        "products":products,
        "section":section,
    }

    return render(request, template, context)

def products_by_brands(request, category_brand, category_slug):

    template = "category/brand_products.html"
    section = "all"
    
    try:
        brand = Brands.objects.filter(slug = category_brand).values_list("id", flat=True)[0]
        category = Category.objects.filter( brands = brand, slug = category_slug).values_list("id", flat=True)[0]
        
    except:
        brand = None
        category = None
    products = get_list_or_404(Products, brand=brand, category = category)

    try:
        if "low" in request.GET["args"]:
            products =Products.objects.filter(brand=brand ,category = category).order_by("price")
            section = "low"
        elif "hight" in request.GET["args"]:
            products =Products.objects.filter(brand=brand, category = category).order_by("-price")
            section = "hight"
        elif "popularity" in request.GET["args"]:
            products = Products.objects.filter(brand=brand, category = category).prefetch_related("productRaiting").order_by("-productRaiting")
            section = "popularity"

        raiting_filters = {
            "starone":Products.objects.filter(
                brand=brand,
                category = category
                ).annotate(
                    products = FilteredRelation(
                        "productRaiting" 
                        )
                    ).filter(products__raiting = 1),
            "startwo":Products.objects.filter(
                brand=brand,
                category = category
                ).annotate(
                    products = FilteredRelation(
                        "productRaiting" 
                        )
                    ).filter(products__raiting = 2),
            "starthree":Products.objects.filter(
                brand=brand,
                category = category
                ).annotate(
                    products = FilteredRelation(
                        "productRaiting" 
                        )
                    ).filter(products__raiting = 3),
            "starfour":Products.objects.filter(
                brand=brand,
                category = category
                ).annotate(
                    products = FilteredRelation(
                        "productRaiting" 
                        )
                    ).filter(products__raiting = 4),
        }
        for key, values in raiting_filters.items():
            if key == request.GET["args"]:
                products = values
                section = key

    except:
        pass
    
    page_num = request.GET.get('page', 1)
    paginator = Paginator(products, 8)

    try:
        products = paginator.page(page_num)
    except PageNotAnInteger:
        # if page is not an integer, deliver the first page
        products = paginator.page(1)
    except EmptyPage:
        # if the page is out of range, deliver the last page
        products = paginator.page(paginator.num_pages)

    context = {
        "products":products,
        "section":section
    }

    return render(request, template, context)

def product(request, product_slug):
    template = "category/product.html"
    product = get_object_or_404(Products, slug=product_slug)

    context = {
        "product":product
    }

    return render(request ,template ,context )

def raiting(request):
    print(request.POST)
    user = CustomUser.objects.get(id = request.user.id)
    product = Products.objects.get(id = request.POST["product"])
    star = request.POST["star"]
    message = request.POST["message"]

    # try:
    instance = ProductRaiting.objects.create(
        user=user,
        product=product,
        raiting=star,
        message=message
    )
    instance.save()
    # except:
    #     pass
    messages.success(request,"Thanks for raiting")
    return HttpResponse(200)

templates/category/brand_products.html
{% extends 'base.html' %}
{% load static %}
{% load tags %}
{% block css %} 
    <link rel="stylesheet" href="{% static 'css/deals.css' %}">
{% endblock %}
{% block content %}
<div class="position-relative mt-md-5 mb-md-5 p-0" style="top: 70px;">
    <div class="row me-0">
        {% include 'category/order_by.html' %}
        <div class="col-lg-9 col-xl-10">
            <div class="card border-0">
                <div class="card-body p-0">
                    <div class="row m-auto me-0">
                        {% for product in products %}
                            <div class="col-md-6 col-lg-4 col-xl-3 mb-3 mb-lg-none d-flex align-items-stretch">
                                <div class="p-3 shadow rounded m-auto m-md-0" style="min-height: 100%;">
                                    <div class="d-flex justify-content-center">
                                        {% if product.productImages.all|len != 0 %}
                                            {% for image in product.productImages.all %}
                                                {% if forloop.first %}
                                                    <a href="{{ product.get_absolute_url }}">
                                                        <img class="img-fluid" src="{{ image.image.url }}" alt="{{ product.name }}" />
                                                    </a>
                                                {% endif %}
                                            {% endfor%}
                                        {% else %}
                                            <a href="{{ product.get_absolute_url }}">
                                                <img class="img-fluid" src="{% static 'Images/No_image.jpg' %}" alt="No Image"/>
                                            </a>
                                        {% endif%}
                                    </div>
                                    <hr>
                                    <h3 class="fs-5">{{ product.name }}</h3>
                                    <div class="text-black d-flex justify-content-start align-items-center">
                                        {% if product.deals.all|len != 0 %}
                                            {% for deal in product.deals.all %}
                                                <div class="fs.2 fw-bold text-decoration-line-through text-danger">{{ product.price }} LEi</div>
                                                <div class="ms-2 fs.2 fw-bold text-primary">{{ product.price|deals:deal}} LEi</div>
                                            {% endfor %}
                                        {% else %}
                                            <div class="fs.2 fw-bold">{{ product.price }} LEi</div>
                                        {% endif %}
                                        <form action="{% url 'cart:cart_add' product.id %}" method='post'>
                                            {{ add_to_cart }}
                                            {% csrf_token %}
                                            <button type="submit" class="ms-3 cart-button" style="background-color: white;border:none;">
                                                <i class="fas fa-shopping-cart text-primary"></i>
                                            </button>
                                        </form>
                                    </div>
                                    <div >
                                        {% if product.deals.all|len != 0 %}
                                            {% for deal in product.deals.all %}
                                                <img class="img-fluid" src="{{ deal.image.url }}" alt="{{ deal.image.url }}" style="max-width: 100px;">
                                                <div class="text-primary">Reducere {{ deal.deal_sum }}{% if deal.deal_choices == 'percent'%}%{% else %}Lei{% endif %}</div>
                                            {% endfor %}
                                        {% endif %}
                                    </div>
                                    <fieldset class="rating">
                                        {% if product.productRaiting.all|len != 0 %}
                                            {% with product.productRaiting.all|raiting as star %}
                                                {% for i in 6|times %}
                                                    {% if i <= star %}
                                                        <input type="radio"  name="rating" value="{{ forloop.counter }}" checked/>
                                                        <label class = "full" ></label>
                                                    {% else %}
                                                        <input type="radio"  name="rating" value="{{ forloop.counter }}"/>
                                                        <label class = "full" ></label>
                                                    {% endif%}
                                                {% endfor %}
                                            {% endwith %}
                                        {% else %}
                                            {% for i in 6|times %}
                                                <input type="radio"  name="rating" value="{{ forloop.counter }}"/>
                                                <label class = "full" ></label>
                                            {% endfor %}
                                        {% endif %}
                                    </fieldset>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% include 'paginator.html' %}
</div>
{% endblock %}

templates/category/category_products.html
{% extends 'base.html' %}
{% load static %}
{% load tags %}
{% block css %} 
    <link rel="stylesheet" href="{% static 'css/deals.css' %}">
{% endblock %}
{% block content %}
<div class="position-relative mt-md-5 mb-md-5 p-0" style="top: 70px;">
    <div class="row me-0">
        {% include 'category/order_by.html' %}
        <div class="col-lg-9 col-xl-10">
            <div class="card border-0">
                <div class="card-body p-0">
                    <div class="row m-auto me-0">
                        {% for product in products %}
                                <div class="col-md-6 col-lg-4 col-xl-3 mb-3 mb-lg-none d-flex align-items-stretch">
                                    <div class="p-3 shadow rounded m-auto m-md-0" style="min-height: 100%;">
                                        <div class="d-flex justify-content-center">
                                            {% if product.productImages.all|len != 0 %}
                                                {% for image in product.productImages.all %}
                                                    {% if forloop.first %}
                                                        <a href="{{ product.get_absolute_url }}">
                                                            <img class="img-fluid" src="{{ image.image.url }}" alt="{{ product.name }}" />
                                                        </a>
                                                    {% endif %}
                                                {% endfor%}
                                            {% else %}
                                                <a href="{{ product.get_absolute_url }}">
                                                    <img class="img-fluid" src="{% static 'Images/No_image.jpg' %}" alt="No Image"/>
                                                </a>
                                            {% endif%}
                                        </div>
                                        <hr>
                                        <h3 class="fs-5" >{{ product.name }}</h3>
                                        <div class="text-black d-flex justify-content-start align-items-center">
                                            {% if product.deals.all|len != 0 %}
                                                {% for deal in product.deals.all %}
                                                    <div class="fs.2 fw-bold text-decoration-line-through text-danger">{{ product.price }} LEi</div>
                                                    <div class="ms-2 fs.2 fw-bold text-primary">{{ product.price|deals:deal}} LEi</div>
                                                {% endfor %}
                                            {% else %}
                                                <div class="fs.2 fw-bold">{{ product.price }} LEi</div>
                                            {% endif %}
                                            <form action="{% url 'cart:cart_add' product.id %}" method='post'>
                                                {{ add_to_cart }}
                                                {% csrf_token %}
                                                <button type="submit" class="ms-3 cart-button" style="background-color: white;border:none;">
                                                    <i class="fas fa-shopping-cart text-primary"></i>
                                                </button>
                                            </form>
                                        </div>
                                        <div >
                                            {% if product.deals.all|len != 0 %}
                                                {% for deal in product.deals.all %}
                                                    <img class="img-fluid" src="{{ deal.image.url }}" alt="{{ deal.image.url }}" style="max-width: 100px;">
                                                    <div class="text-primary">Reducere {{ deal.deal_sum }}{% if deal.deal_choices == 'percent'%}%{% else %}Lei{% endif %}</div>
                                                {% endfor %}
                                            {% endif %}
                                        </div>
                                        <fieldset class="rating">
                                            {% if product.productRaiting.all|len != 0 %}
                                                {% with product.productRaiting.all|raiting as star %}
                                                    {% for i in 6|times %}
                                                        {% if i <= star %}
                                                            <input type="radio"  name="rating" value="{{ forloop.counter }}" checked/>
                                                            <label class = "full" ></label>
                                                        {% else %}
                                                            <input type="radio"  name="rating" value="{{ forloop.counter }}"/>
                                                            <label class = "full" ></label>
                                                        {% endif%}
                                                    {% endfor %}
                                                {% endwith %}
                                            {% else %}
                                                {% for i in 6|times %}
                                                    <input type="radio"  name="rating" value="{{ forloop.counter }}"/>
                                                    <label class = "full" ></label>
                                                {% endfor %}
                                            {% endif %}
                                        </fieldset>
                                    </div>
                                </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% include 'paginator.html' %}
</div>
{% endblock %}

templates/category/order_by.html
<div class="col-lg-3 col-xl-2 border-end border-bottom mb-2 p-xl-0">
    <div class="row m-auto">
        <div class="col-7 col-md-4 col-lg-12 mb-5">
            <p class="fs-5">Category</p>
            <ul class="list-group list-group-flush" style="max-height: 160px; overflow: auto; ">
                {% for category in categorys%}
                    <li class="list-group-item {% if category.title in request.path  %}active{% endif %}">
                        <a class="text-decoration-none {% if category.title in request.path  %}text-white{% else %}text-muted{% endif %}" href="{% url 'category:products_category' category.slug %}">{{ category.title }}</a>
                    </li>
                {% endfor %}
            </ul>
        </div>
        <div class="col-7 col-md-4 col-lg-12 mb-5">
            <p class="fs-5">Order by</p>
            <ul class="list-group list-group-flush">
                <li class="list-group-item {% if section == 'all' %}active{% endif %}">
                    <a class="text-decoration-none {% if section == 'all' %}text-white{% else %}text-muted{% endif %}" href="{{ request.path }}">All Products</a>
                </li>
                <li class="list-group-item {% if section == 'popularity' %}active{% endif %}">
                    <a class="text-decoration-none {% if section == 'popularity' %}text-white{% else %}text-muted{% endif %}" href="{{ request.path }}?args=popularity">Popularity</a>
                </li>
                <li class="list-group-item {% if section == 'low' %}active{% endif %}">
                    <a class="text-decoration-none {% if section == 'low' %}text-white{% else %}text-muted{% endif %}" href="{{ request.path }}?args=low">Price: low to high</a> 
                </li>
                <li class="list-group-item {% if section == 'hight' %}active{% endif %}">
                    <a class="text-decoration-none {% if section == 'hight' %}text-white{% else %}text-muted{% endif %}" href="{{ request.path }}?args=hight">Price: high to low</a> 
                </li>
            </ul>
        </div>
        <div class="col-7 col-md-4 col-lg-12 mb-5">
            <p class="fs-5">Order by Raiting</p>
            <ul class="list-group list-group-flush ">
                <li class="list-group-item d-flex align-items-center justify-content-between p-0 {% if section == 'starfour' %}border-primary{% endif %}">
                    <div class="rating">
                        <input type="radio"  name="rating" checked/>
                        <label class = "full" ></label>
                        <input type="radio"  name="rating" checked/>
                        <label class = "full" ></label>
                        <input type="radio"  name="rating" checked/>
                        <label class = "full" ></label>
                        <input type="radio"  name="rating" checked/>
                        <label class = "full" ></label>
                        <input type="radio"  name="rating" />
                        <label class = "full" ></label>
                    </div>
                    <a class="text-decoration-none text-muted" href="{{ request.path }}?args=starfour">
                        <i class="fas fa-chevron-right fa-fw d-fa-preview" style="font-weight: 900;"></i>
                    </a>
                </li>
                <li class="list-group-item d-flex align-items-center justify-content-between p-0 {% if section == 'starthree' %}border-primary{% endif %}">
                    <div class="rating">
                        <input type="radio"  name="rating" checked/>
                        <label class = "full" ></label>
                        <input type="radio"  name="rating" checked/>
                        <label class = "full" ></label>
                        <input type="radio"  name="rating" checked/>
                        <label class = "full" ></label>
                        <input type="radio"  name="rating" />
                        <label class = "full" ></label>
                        <input type="radio"  name="rating" />
                        <label class = "full" ></label>
                    </div>
                    <a class="text-decoration-none text-muted" href="{{ request.path }}?args=starthree">
                        <i class="fas fa-chevron-right fa-fw d-fa-preview" style="font-weight: 900;"></i>
                    </a>
                </li>
                <li class="list-group-item d-flex align-items-center justify-content-between p-0 {% if section == 'startwo' %}border-primary{% endif %}">
                    <div class="rating">
                        <input type="radio"  name="rating" checked/>
                        <label class = "full" ></label>
                        <input type="radio"  name="rating" checked/>
                        <label class = "full" ></label>
                        <input type="radio"  name="rating" />
                        <label class = "full" ></label>
                        <input type="radio"  name="rating" />
                        <label class = "full" ></label>
                        <input type="radio"  name="rating" />
                        <label class = "full" ></label>
                    </div>
                    <a class="text-decoration-none text-muted" href="{{ request.path }}?args=startwo">
                        <i class="fas fa-chevron-right fa-fw d-fa-preview" style="font-weight: 900;"></i>
                    </a>
                </li>
                <li class="list-group-item d-flex align-items-center justify-content-between p-0 {% if section == 'starone' %}border-primary{% endif %}">
                    <div class="rating">
                        <input type="radio"  name="rating" checked/>
                        <label class = "full" ></label>
                        <input type="radio"  name="rating" />
                        <label class = "full" ></label>
                        <input type="radio"  name="rating" />
                        <label class = "full" ></label>
                        <input type="radio"  name="rating" />
                        <label class = "full" ></label>
                        <input type="radio"  name="rating" />
                        <label class = "full" ></label>
                    </div>
                    <a class="text-decoration-none text-muted" href="{{ request.path }}?args=starone">
                        <i class="fas fa-chevron-right fa-fw d-fa-preview" style="font-weight: 900;"></i>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</div>