accounts/urls.py
from django.urls import path
from django.contrib.auth.views import(
    LoginView,
    LogoutView
) 
from .views import *
from .forms import *

app_name = "accounts"

urlpatterns = [
    path("login/", LoginView.as_view(form_class = CustomAuthentificationForm ,template_name = "accounts/login.html"), name="login"),
    path("register/", register, name="register"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("orders/", downloadOrders, name="orders"),
]

category/urls.py
from django.urls import path
from .views import *

app_name = "category"

urlpatterns = [
    path("raiting", raiting, name="raiting"),
    path("product/<product_slug>", product, name="product"),
    path("<slug>", products_by_category, name="products_category"),
    path("<category_brand>/<category_slug>", products_by_brands, name="product_brands"),
]

home/urls.py
from django.urls import path, re_path
from .views import *

app_name = "home"
dispach = lambda path : path if "popularity" in path else ""
urlpatterns = [
    path("", home, name="home"),
    path("popularity", home, name="homePopularity"),
]

orders/urls.py
from django.urls import path
from .views import *

app_name = "cart"

urlpatterns = [
    path("", cart, name="cart"),
    path("checkout", Checkout.as_view(), name="checkout"),
    path("download/<int:order_id>", generatePdf, name="download"),
    path('add/<int:product_id>/', cart_add, name='cart_add'),
    path('decrease/<int:product_id>/', cart_decrease, name='cart_decrease'),
    path('remove/<int:product_id>/', cart_remove, name='cart_remove'),
]

setup/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import  static
from django.conf import settings
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("home.urls")),
    path("accounts/", include("accounts.urls")),
    path("category/", include("category.urls")),
    path("cart/", include("orders.urls")),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}, name='static'),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}, name='media'),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/base.html
{% load static %}
{% load bootstrap5 %}
{% load fontawesome_5 %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block css %} {% endblock %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    {% fontawesome_5_static %}
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <title>Document</title>
</head>
<body>
    {% include 'navbar.html' %}
    {% include 'messages.html' %}
    {% include 'sidebar.html' %}


        {% block content %}
        {% endblock %}

    
    {% include 'footer.html' %}
    {% include 'scripts.html' %}

    {% block scripts %} {% endblock %}
</body>
</html>

templates/footer.html
<footer class="footer mt-auto py-3 bg-light position-relative bg-white" style="top: 70px;">
  <div class="bg-primary">

    <div class="container text-white">

      <!-- Grid row -->
      <div class="row py-4 d-flex align-items-center">

        <!-- Grid column -->
        <div class="col-md-6 col-lg-5 text-center text-md-left mb-4 mb-md-0">

          <h6 class="mb-0 ">Get connected with us on social networks!</h6>

        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-6 col-lg-7 text-center text-md-right">

          <!-- Facebook -->
          <a class="fb-ic ml-0 px-2"><i class="fab fa-facebook-f text-white"> </i></a>

          <!-- Twitter -->
          <a class="tw-ic px-2"><i class="fab fa-twitter text-white"> </i></a>

          <!-- Google + -->
          <a class="gplus-ic px-2"><i class="fab fa-google-plus-g text-white"> </i></a>

          <!-- Linkedin -->
          <a class="li-ic px-2"><i class="fab fa-linkedin-in text-white"> </i></a>

          <!-- Instagram -->
          <a class="ins-ic px-2"><i class="fab fa-instagram text-white"> </i></a>

        </div>
        <!-- Grid column -->

      </div>
      <!-- Grid row -->

    </div>

  </div>

  <!-- Footer Links -->
  <div class="container mt-5 mb-4 text-center text-md-left">

    <div class="row mt-3">

      <!-- First column -->
      <div class="col-md-3 col-lg-4 col-xl-3 mb-4">

        <h6 class="text-uppercase font-weight-bold"><strong>Company name</strong></h6>

        <hr class="blue mb-4 mt-0 d-inline-block mx-auto" style="width: 60px;">

        <p>Here you can use rows and columns here to organize your footer content. Lorem ipsum dolor sit amet,

          consectetur

          adipisicing elit.</p>

      </div>
      <!-- First column -->

      <!-- Second column -->
      <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">

        <h6 class="text-uppercase font-weight-bold"><strong>Products</strong></h6>

        <hr class="blue mb-4 mt-0 d-inline-block mx-auto" style="width: 60px;">

        <p><a class="text-decoration-none text-black" href="#!">link </a></p>

        <p><a class="text-decoration-none text-black" href="#!">link</a></p>

        <p><a class="text-decoration-none text-black" href="#!">link</a></p>

        <p><a class="text-decoration-none text-black" href="#!">link</a></p>

      </div>
      <!-- Second column -->

      <!-- Third column -->
      <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">

        <h6 class="text-uppercase font-weight-bold"><strong>Useful links</strong></h6>

        <hr class="blue mb-4 mt-0 d-inline-block mx-auto" style="width: 60px;">

        <p><a class="text-decoration-none text-black" href="#!">Your Account</a></p>

        <p><a class="text-decoration-none text-black" href="#!">Become an Affiliate</a></p>

        <p><a class="text-decoration-none text-black" href="#!">Shipping Rates</a></p>

        <p><a class="text-decoration-none text-black" href="#!">Help</a></p>

      </div>
      <!-- Third column -->

      <!-- Fourth column -->
      <div class="col-md-4 col-lg-3 col-xl-3">

        <h6 class="text-uppercase font-weight-bold"><strong>Contact</strong></h6>

        <hr class="blue mb-4 mt-0 d-inline-block mx-auto" style="width: 60px;">

        <p><i class="fas fa-home mr-3"></i> New York, NY 10012, US</p>

        <p><i class="fas fa-envelope mr-3"></i> info@example.com</p>

        <p><i class="fas fa-phone mr-3"></i> + 01 234 567 88</p>

        <p><i class="fas fa-print mr-3"></i> + 01 234 567 89</p>

      </div>
      <!-- Fourth column -->

    </div>

  </div>
  <!-- Footer Links -->

  <!-- Copyright -->
  <div class="footer-copyright py-3 text-center">

    <div class="container-fluid">

      © 2019 Copyright: <a class="text-reset text-decoration-none" href="https://laurentiumarian.ro" target="_blank"> Laurentiu Marian Baluta </a>

    </div>

  </div>
  <!-- Copyright -->

</footer>

templates/messages.html
<style>
    .alert{
        transform: translateY(-100%);
        border-radius: 0;
    }
    .show-messages{
        transform: translateY(0);
        transition: all 0.5s;
    }
</style>

{% if messages %} 
{% for message in messages %}
    <div id="message" class="alert alert-{{ message.tags }} position-relative" role="alert" style="top: 70px;">
        {{ message }}
    </div>
{% endfor %}
{% endif %}

templates/navbar.html
{% load tags %}

<nav id="headernav" class="navbar navbar-expand-lg navbar-light bg-white fixed-top border-bottom">
  <div class="container-lg bg-white flex-row">
    <button id="sidebarbutton" class="btn btn-light text-primary d-md-none bg-white">
      <i class="fas fa-bars"></i>
    </button>
    <a class="navbar-brand col-lg-8" href="{% url 'home:home' %}">e-commerce</a>
    <button class="btn btn-light text-primary d-lg-none bg-white" type="button" data-bs-toggle="collapse"
      data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
      aria-label="Toggle navigation">
      <i class="fas fa-bars"></i>
    </button>
    <div class="collapse navbar-collapse col-lg-4" id="navbarSupportedContent">
      <ul class="navbar-nav m-auto mb-2 mb-lg-0 w-100 justify-content-end">
        {% if request.user.is_authenticated %}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown"
              aria-expanded="false">
              <i class="fas fa-user text-primary"></i>
              Profile
            </a>
            <ul class="dropdown-menu position-absolute" aria-labelledby="navbarDropdown">
              <li><a class="dropdown-item" href="{% url 'accounts:orders' %}">Your Orders</a></li>
              <li>
                <hr class="dropdown-divider">
              </li>
              <li><a class="dropdown-item" href="{% url 'accounts:logout' %}">Logout</a></li>
            </ul>
          </li>
        {% else %}
          <li class="nav-item dropdown">
            <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
          </li>
        {% endif %}
        <li class="nav-item d-flex">
          <a class="nav-link" type="button" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
            <i class="fas fa-shopping-cart text-primary"></i>
            {% if cart %}
              <span class="text-white mx-1 bg-danger rounded text-center" style="padding-left: 5px;">
                {{ cart.cart_products }}
              </span>
            {% endif %}
            Cart
          </a>
        </li>
      </ul>
    </div>
  </div>
</nav>
<div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="staticBackdropLabel">Cart</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <ul id="cart_list" class="list-group list-group-flush">
          {% if cart %}
            {% for item in cart %}
              {% with product=item.product %}
              <li class="list-group-item">
                <div class="d-md-flex justify-content-between text-center">
                  <div class="d-none d-md-block">
                    {{ forloop.counter }}
                  </div>
                  <div>
                    {{ product.name }}
                  </div>
                  <div>
                    {% if product.deals.all|len != 0 %}
                        {% for deal in product.deals.all %}
                            <div class="fs.2 fw-bold text-decoration-line-through text-danger">{{ product.price }} LEi</div>
                            <div class="ms-2 fs.2 fw-bold text-primary">{{ product.price|deals:deal}} LEi</div>
                        {% endfor %}
                    {% else %}
                        <div class="fs.2 fw-bold">{{ product.price }} LEi</div>
                    {% endif %}
                  </div>
                  <form action='{% url "cart:cart_remove" product.id %}' method="post">
                    <button class="cart-remove-product" type="submit" style="background-color: white;border:none;">
                      <i class="fas fa-trash "></i>
                    </button>
                    {% csrf_token %}
                  </form>
                </div>
              </li>
              {% endwith %}
            {% endfor %}
          {% else %}
          <li class="list-group-item">No Products</li>
          {% endif %}
        </ul>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        {% if cart %}
          <a href="{% url 'cart:cart' %}" type="button" class="btn btn-primary">Checkout</a>
        {% endif %}
      </div>
    </div>
  </div>
</div>

templates/paginator.html
{% if products.has_other_pages %}
    <nav class="d-flex justify-content-center my-3">
        <ul class="pagination">
            {% if products.has_previous %}
                <li class="page-item"><a class="page-link" href="?page={{ products.previous_page_number }}">&laquo;</a></li>
            {% else %}
                <li class="page-item disabled"><span class="page-link">&laquo;</span></li>
            {% endif %}
            {% for i in products.paginator.page_range %}
                {% if products.number == i %}
                    <li class="page-item active"><span class="page-link">{{ i }} <span class="sr-only">(current)</span></span></li>
                {% else %}
                    <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                {% endif %}
            {% endfor %}
            {% if products.has_next %}
                <li class="page-item"><a class="page-link" href="?page={{ products.next_page_number }}">&raquo;</a></li>
            {% else %}
                <li class="page-item disabled"><span class="page-link">&raquo;</span></li>
            {% endif %}
        </ul>
    </nav>
{% endif %}

templates/scripts.html
{% load static %}

<script src="{% static 'js/base.js' %}"></script>

templates/sidebar.html
{% load static %}
{% load tags %}

<div id="sidebar" class="fixed-top w-100 h-100 sidebarclose d-md-none">
  <div id="insideSidebar" class="d-flex flex-column flex-shrink-0 p-3 bg-white h-100" style="width: 50%;">
    <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto link-dark text-decoration-none">
      <svg class="bi me-2" width="40" height="32"><use xlink:href="#bootstrap"></use></svg>
      <span class="fs-4">Category</span>
    </a>
    <div>
      <input id="search" class="form-select nosubmit" placeholder="Search" onkeyup="search_products()">
      <div class="position-relative w-100 d-none" id="browse">
        <div class="position-absolute card w-100 bg-light overflow-auto" style="max-height: 300px;">
          {% for product in products %}
            <div class="search-item">
              <a class="nav-link text-black" href="{{ product.get_absolute_url }}">
                {{ product.name }}</a>
            </div>
          {% endfor %}
        </div>
      </div>  
    </div>
    <ul class="nav nav-pills flex-column mb-auto">
      {% for category in categorys %}
        <li class="nav-item ">
            <a class="nav-link dropdown-toggle text-black" href="#" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="true">
                {% if category.svg %}
                    {{ category.svg|safe }}
                    
                {% else %}
                    {{ category.image.as_html }}
                {% endif %}
                {{ category.title }}
            </a>
        
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                {% for brands in category.brands.all%}
                  <li><a class="dropdown-item" href="{% url 'category:product_brands' brands.slug category.slug %}">{{ brands.title}}</a></li>
                {% endfor %}
            </ul>
        </li>
      {% endfor %}
    </ul>
    <hr>
    <div class="dropdown">
      <a href="#" class="d-flex align-items-center link-dark text-decoration-none dropdown-toggle" id="dropdownUser2" data-bs-toggle="dropdown" aria-expanded="false">
        <img src="https://github.com/mdo.png" alt="" width="32" height="32" class="rounded-circle me-2">
        <strong>mdo</strong>
      </a>
      <ul class="dropdown-menu text-small shadow" aria-labelledby="dropdownUser2">
        <li><a class="dropdown-item" href="#">New project...</a></li>
        <li><a class="dropdown-item" href="#">Settings</a></li>
        <li><a class="dropdown-item" href="#">Profile</a></li>
        <li><hr class="dropdown-divider"></li>
        <li><a class="dropdown-item" href="#">Sign out</a></li>
      </ul>
    </div>
  </div>
</div>